In [1]:
%run kobeshot_2.py

/home/z/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


100 1.6765953
200 0.50610375
300 0.46278116
400 0.44215935
500 0.4064795
600 0.39911434
700 0.39510894
800 0.38579777
900 0.37930393
1000 0.3741825
1100 0.3698694
1200 0.36608878
1300 0.3627532
1400 0.35992968
1500 0.3574072
1600 0.3552082
1700 0.35314816
1800 0.35132346
1900 0.34975645
2000 0.34811756
2100 0.34470302
2200 0.33886868
2300 0.3345167
2400 0.33155018
2500 0.32941514
2600 0.32775953
2700 0.326368
2800 0.32515943
2900 0.32411647
3000 0.32318637
3100 0.32231545
3200 0.32152689
3300 0.32080877
3400 0.32013866
3500 0.31953183
3600 0.31898034
3700 0.31847015
3800 0.3180005
3900 0.31755474
4000 0.3171463
4100 0.31675503
4200 0.31640235
4300 0.3160695
4400 0.3157371
4500 0.31543806
4600 0.3151512
4700 0.3148508
4800 0.31456667
4900 0.3142923
5000 0.31403866
5100 0.31378385
5200 0.31353822
5300 0.31330204
5400 0.3130976
5500 0.31288576
5600 0.3126807
5700 0.31247914
5800 0.31229442
5900 0.31211582
6000 0.3119459
6100 0.31178147
6200 0.3116236
6300 0.31146735
6400 0.31131506
6500 0

In [50]:
%run kobeshot.py

100 1.557
200 1.525683
300 1.5023024
400 1.4808166
500 1.453868
600 1.4254184
700 1.4116769
800 1.4031876
900 1.3962132
1000 1.3895113
1100 1.3832604
1200 1.3770725
1300 1.370498
1400 1.3644967
1500 1.357365
1600 1.3489226
1700 1.3388522
1800 1.3294661
1900 1.3219385
2000 1.3143688
2100 1.3059639
2200 1.2975113
2300 1.2889857
2400 1.2824849
2500 1.2760154
2600 1.2717017
2700 1.2675655
2800 1.2636477
2900 1.2601196
3000 1.2567613
3100 1.2528222
3200 1.2451131
3300 1.2380387
3400 1.2341888
3500 1.2313809
3600 1.228916
3700 1.2269813
3800 1.2253191
3900 1.2238418
4000 1.2221994
4100 1.2207699
4200 1.2195451
4300 1.2184595
4400 1.2173058
4500 1.2158468
4600 1.2147359
4700 1.2140481
4800 1.2133875
4900 1.2127398
5000 1.2121356
5100 1.2115726
5200 1.2110515
5300 1.2105544
5400 1.2100724
5500 1.2096035
5600 1.2091526
5700 1.2087286
5800 1.2083262
5900 1.2079417
6000 1.2075713
6100 1.2072123
6200 1.2068648
6300 1.2065283
6400 1.2061988
6500 1.2058607
6600 1.2055126
6700 1.2052003
6800 1.204917

In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 16 19:47:19 2018

@author: z

using CNN
"""

#kobe_dataset
import pandas as pd
import tensorflow as tf

x_data = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs'])

x_data = x_data.values
y_data = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y_data = y_data.values

x_test = x_data[30000:30600,:]
y_test = y_data[30000:30600,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([5, 5], -1., 1.))

W2 = tf.Variable(tf.random_uniform([5, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([5]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 100 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))



100 0.639463
200 0.5571978
300 0.5158772
400 0.4883922
500 0.4682296
600 0.45246348
700 0.43935928
800 0.42808974
900 0.4183812
1000 0.41014835
1100 0.4031856
1200 0.39692345
1300 0.39186043
1400 0.3872121
1500 0.38250598
1600 0.37900227
1700 0.37624243
1800 0.37381095
1900 0.3716429
2000 0.36969066
2100 0.36792305
2200 0.36630917
2300 0.3648326
2400 0.36347297
2500 0.36221382
2600 0.36105344
2700 0.35997203
2800 0.358964
2900 0.3580245
3000 0.3571448
3100 0.35632515
3200 0.3555558
3300 0.35483283
3400 0.35415465
3500 0.3535119
3600 0.35290736
3700 0.352335
3800 0.35179308
3900 0.3512802
4000 0.35079113
4100 0.3503259
4200 0.3498853
4300 0.34946644
4400 0.3490611
4500 0.34867963
4600 0.3483136
4700 0.34796196
4800 0.34762743
4900 0.34730336
5000 0.34699336
5100 0.34669665
5200 0.34639502
5300 0.34611553
5400 0.345849
5500 0.34559178
5600 0.34534416
5700 0.34510678
5800 0.34487447
5900 0.34465498
6000 0.3444418
6100 0.34423712
6200 0.3440421
6300 0.34384844
6400 0.343664
6500 0.34348106

In [4]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 16 19:47:19 2018

@author: z

using CNN
"""

#kobe_dataset
import pandas as pd
import tensorflow as tf

x_data = pd.read_csv('kobe_data.csv',usecols=['shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x_data = x_data.values
y_data = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y_data = y_data.values

x_test = x_data[30000:30600,:]
y_test = y_data[30000:30600,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([7, 9], -1., 1.))

W2 = tf.Variable(tf.random_uniform([9, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([9]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 100 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))



100 0.66172236
200 0.50853115
300 0.4502756
400 0.4227604
500 0.4071593
600 0.39693475
700 0.3894647
800 0.38353556
900 0.37859368
1000 0.3743458
1100 0.37059972
1200 0.3672488
1300 0.36424446
1400 0.36155993
1500 0.35917127
1600 0.3570446
1700 0.35516876
1800 0.35351595
1900 0.35214344
2000 0.3509253
2100 0.3498269
2200 0.34883833
2300 0.34795603
2400 0.34715772
2500 0.34643966
2600 0.3457844
2700 0.3451879
2800 0.34464404
2900 0.34414205
3000 0.34368017
3100 0.3432568
3200 0.34285846
3300 0.34248647
3400 0.34214255
3500 0.3418246
3600 0.3415252
3700 0.34124535
3800 0.3409832
3900 0.3407373
4000 0.34050506
4100 0.34028506
4200 0.34007683
4300 0.33988184
4400 0.33969465
4500 0.33951727
4600 0.3393477
4700 0.3391879
4800 0.3390358
4900 0.33889213
5000 0.33875164
5100 0.3386204
5200 0.33849388
5300 0.33837652
5400 0.3382619
5500 0.33815184
5600 0.338044
5700 0.33794212
5800 0.3378437
5900 0.33774844
6000 0.33765897
6100 0.33757007
6200 0.33748713
6300 0.3374074
6400 0.3373274
6500 0.3372

In [ ]:
#kobe_dataset
import pandas as pd
import tensorflow as tf

x_data = pd.read_csv('kobe_data.csv',usecols=['shot_distance',
'shot_zone_area','period','minutes_remaining','seconds_remaining'])

x_data = x_data.values
y_data = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y_data = y_data.values

x_test = x_data[30000:30600,:]
y_test = y_data[30000:30600,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([5, 9], -1., 1.))

W2 = tf.Variable(tf.random_uniform([9, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([9]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 100 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))


100 1.0763427
200 0.680093
300 0.54924375
400 0.48282358
500 0.43828353
600 0.4093338
700 0.39036623
800 0.3787408
900 0.37119833
1000 0.36650062
1100 0.36318222
1200 0.3606838
1300 0.35896274
1400 0.35751918
1500 0.35640043
1600 0.35528916
1700 0.35443318
1800 0.35364288
1900 0.3529409
2000 0.35233837
2100 0.35170856
2200 0.35104555
2300 0.35056773
2400 0.35007846
2500 0.34984812
2600 0.34937114
2700 0.34880555
2800 0.3483169
2900 0.34784952
3000 0.34740946
3100 0.34696358
3200 0.34649757
3300 0.34609422
3400 0.34571642
3500 0.34540612
3600 0.34503737
3700 0.34452468
3800 0.3440554
3900 0.34359097
4000 0.34312728
4100 0.34256274
4200 0.34200868
4300 0.34135398
4400 0.3406671
4500 0.33946618
4600 0.33810726
4700 0.3365899
4800 0.33558148
4900 0.33483288
5000 0.33411875
5100 0.33334306
5200 0.33279943
5300 0.33223277
5400 0.33153743
5500 0.330995
5600 0.33047533
5700 0.33007786
5800 0.32975468
5900 0.32937142
6000 0.32916018
6100 0.32914445
6200 0.3286531
6300 0.32823923
6400 0.3279235


In [6]:
#kobe_dataset
import pandas as pd
import tensorflow as tf

x_data = pd.read_csv('kobe_data.csv',usecols=['shot_distance','shot_zone_area','period'])

x_data = x_data.values
y_data = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y_data = y_data.values

x_test = x_data[30000:30600,:]
y_test = y_data[30000:30600,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([3, 5], -1., 1.))

W2 = tf.Variable(tf.random_uniform([5, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([5]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 100 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))

100 0.7232901
200 0.5906161
300 0.52671814
400 0.487615
500 0.4590911
600 0.4367727
700 0.41863278
800 0.40358782
900 0.3911649
1000 0.38095573
1100 0.37264696
1200 0.36595994
1300 0.36061797
1400 0.3563653
1500 0.35296482
1600 0.350232
1700 0.34806275
1800 0.34634352
1900 0.3449068
2000 0.34367427
2100 0.34259766
2200 0.3416394
2300 0.3407713
2400 0.33997765
2500 0.3392582
2600 0.33858934
2700 0.33795917
2800 0.33736107
2900 0.3367904
3000 0.3362452
3100 0.33572006
3200 0.3352157
3300 0.33473358
3400 0.33426607
3500 0.33381295
3600 0.33337167
3700 0.33294153
3800 0.3325218
3900 0.3321144
4000 0.33171526
4100 0.33132833
4200 0.33094934
4300 0.33057812
4400 0.33021697
4500 0.32986265
4600 0.32951647
4700 0.32917792
4800 0.3288471
4900 0.32852283
5000 0.32820582
5100 0.3278957
5200 0.32759187
5300 0.3272949
5400 0.32700312
5500 0.32672006
5600 0.32644248
5700 0.32616857
5800 0.325901
5900 0.32563937
6000 0.3253835
6100 0.3251299
6200 0.32488254
6300 0.32464066
6400 0.32440227
6500 0.3241

In [7]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 16 19:47:19 2018

@author: z

using CNN
"""

#kobe_dataset
import pandas as pd
import tensorflow as tf

x_data = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x_data = x_data.values
y_data = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y_data = y_data.values

x_test = x_data[30000:30600,:]
y_test = y_data[30000:30600,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([9, 9], -1., 1.))

W2 = tf.Variable(tf.random_uniform([9, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([9]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 100 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))



100 0.6539798
200 0.53434026
300 0.47081205
400 0.47884414
500 0.43691474
600 0.4346113
700 0.4150166
800 0.42153683
900 0.4269739
1000 0.39798802
1100 0.39109156
1200 0.38615635
1300 0.3772827
1400 0.3733581
1500 0.3719165
1600 0.37070006
1700 0.36342886
1800 0.35897776
1900 0.35845068
2000 0.35352504
2100 0.35054275
2200 0.3480966
2300 0.3477152
2400 0.34547904
2500 0.34935758
2600 0.39172933
2700 0.34021595
2800 0.33903694
2900 0.34413478
3000 0.33770683
3100 0.3374256
3200 0.34352276
3300 0.33629823
3400 0.33320174
3500 0.34405306
3600 0.3320653
3700 0.32967278
3800 0.32833156
3900 0.32851216
4000 0.3235103
4100 0.32309666
4200 0.32023263
4300 0.3196996
4400 0.32081565
4500 0.31878513
4600 0.3176903
4700 0.31717137
4800 0.3149257
4900 0.3223627
5000 0.31485707
5100 0.31185493
5200 0.31496757
5300 0.3104182
5400 0.31062117
5500 0.31201264
5600 0.31002498
5700 0.30868354
5800 0.30902493
5900 0.30867767
6000 0.30913794
6100 0.30841026
6200 0.30742988
6300 0.3069958
6400 0.30975893
650

In [2]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 16 19:47:19 2018

@author: z

using CNN
"""

#kobe_dataset
import pandas as pd
import tensorflow as tf

x_data = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x_data = x_data.values
y_data = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y_data = y_data.values

x_test = x_data[30000:30600,:]
y_test = y_data[30000:30600,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([9, 3], -1., 1.))

W2 = tf.Variable(tf.random_uniform([3, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([3]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 100 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))


100 0.537771
200 0.4975066
300 0.46783185
400 0.44357392
500 0.42356706
600 0.40785846
700 0.39538762
800 0.38558573
900 0.378087
1000 0.37264606
1100 0.36885324
1200 0.36620244
1300 0.36421576
1400 0.36259565
1500 0.36118504
1600 0.35991248
1700 0.35875648
1800 0.3576816
1900 0.35664517
2000 0.3556509
2100 0.35468358
2200 0.35373676
2300 0.3528104
2400 0.35192516
2500 0.3510962
2600 0.35030615
2700 0.34953496
2800 0.34880677
2900 0.3480894
3000 0.34739894
3100 0.34670988
3200 0.34605393
3300 0.34542537
3400 0.34480608
3500 0.34421158
3600 0.34364194
3700 0.34309107
3800 0.3425689
3900 0.34206623
4000 0.34159023
4100 0.341131
4200 0.34067994
4300 0.3402493
4400 0.3398215
4500 0.3393923
4600 0.3389584
4700 0.3385358
4800 0.3381269
4900 0.33773538
5000 0.3373569
5100 0.33699
5200 0.33664107
5300 0.33630598
5400 0.33598384
5500 0.3356669
5600 0.33535567
5700 0.3350544
5800 0.33476433
5900 0.33446828
6000 0.33417284
6100 0.33387354
6200 0.33358085
6300 0.33329377
6400 0.3329996
6500 0.3326

In [1]:
#kobe_dataset
import pandas as pd
import tensorflow as tf

x_data = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x_data = x_data.values
y_data = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y_data = y_data.values

x_test = x_data[25000:30600,:]
y_test = y_data[25000:30600,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([9, 9], -1., 1.))

W2 = tf.Variable(tf.random_uniform([9, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([9]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 1000 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))


1000 0.33286336
2000 0.30836788
3000 0.30534348
4000 0.30412433
5000 0.303533
6000 0.303235
7000 0.30303422
8000 0.30288857
9000 0.3027758
10000 0.30268985
11000 0.30262467
12000 0.30257955
13000 0.3025384
14000 0.3025092
15000 0.30248767
16000 0.3024575
17000 0.30244136
18000 0.30241883
19000 0.30239433
20000 0.30237284
21000 0.30236617
22000 0.30234957
23000 0.30235136
24000 0.3023353
25000 0.30231956
26000 0.30231386
27000 0.30230486
28000 0.30229524
29000 0.30228764
30000 0.30227217
accuracy: 88.82


In [2]:
#kobe_dataset
import pandas as pd
import tensorflow as tf

x = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x =x.values
y = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y = y.values

x_data = x[5000:30600,:]
y_data = y[5000:30600,:]


x_test = x[0:5000,:]
y_test = y[0:5000,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([9, 9], -1., 1.))

W2 = tf.Variable(tf.random_uniform([9, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([9]))

b2 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L1 = tf.nn.relu(L1)

model = tf.add(tf.matmul(L1, W2), b2)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 1000 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))


1000 0.32776612
2000 0.29822546
3000 0.28945595
4000 0.2854652
5000 0.2841113
6000 0.28208718
7000 0.28140458
8000 0.28157
9000 0.28113422
10000 0.2814775
11000 0.2812075
12000 0.281309
13000 0.28136882
14000 0.28124171
15000 0.28137872
16000 0.28123856
17000 0.28099328
18000 0.28100932
19000 0.2809997
20000 0.2809856
21000 0.28088838
22000 0.28096858
23000 0.28089592
24000 0.28091
25000 0.28074345
26000 0.2806847
27000 0.2806627
28000 0.28072613
29000 0.28065097
30000 0.28065223
accuracy: 86.54


In [3]:
#kobe_dataset
import pandas as pd
import tensorflow as tf

x = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x =x.values
y = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y = y.values

x_data = x[5000:30600,:]
y_data = y[5000:30600,:]


x_test = x[0:5000,:]
y_test = y[0:5000,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([9, 8], -1., 1.))

W2 = tf.Variable(tf.random_uniform([8, 7], -1., 1.))

W3 = tf.Variable(tf.random_uniform([7, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([8]))

b2 = tf.Variable(tf.zeros([7]))

b3 = tf.Variable(tf.zeros([6]))

L1 = tf.add(tf.matmul(X, W1), b1)

L2 = tf.add(tf.matmul(L1, W2), b2)

L2 = tf.nn.relu(L2)

model = tf.add(tf.matmul(L2, W3), b3)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 1000 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))

1000 0.7729189
2000 0.75060385
3000 0.7493384
4000 0.7490172
5000 0.74889296
6000 0.74883604
7000 0.7488355
8000 0.7488211
9000 0.748833
10000 0.7488179
11000 0.7488175
12000 0.7488156
13000 0.7488228
14000 0.7488231
15000 0.7488273
16000 0.7488281
17000 0.7488272
18000 0.748828
19000 0.7488282
20000 0.7488284
21000 0.74878955
22000 0.7487892
23000 0.7487894
24000 0.7487899
25000 0.74879044
26000 0.7487905
27000 0.74879044
28000 0.74879026
29000 0.74879026
30000 0.7487902
accuracy: 71.20


In [4]:
#kobe_dataset
import pandas as pd
import tensorflow as tf

x = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x =x.values
y = pd.read_csv('kobe_data.csv',usecols=['t1','t2','t3','t4','t5','t6'])
y = y.values

x_data = x[5000:30600,:]
y_data = y[5000:30600,:]


x_test = x[0:5000,:]
y_test = y[0:5000,:]

X = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([9, 6], -1., 1.))

b1 = tf.Variable(tf.zeros([6]))

model = tf.add(tf.matmul(X, W1), b1)

cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=model))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(30000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 1000 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)

#print('Predicted value:', sess.run(prediction, feed_dict={X: x_test}))
#print('Actual value:', sess.run(target, feed_dict={Y: y_test}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('accuracy: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_test, Y: y_test}))

1000 0.35644096
2000 0.34655938
3000 0.34314987
4000 0.34218627
5000 0.34173942
6000 0.34140763
7000 0.3411248
8000 0.34087765
9000 0.34065986
10000 0.34046677
11000 0.34029418
12000 0.34013885
13000 0.3399987
14000 0.33987153
15000 0.33975592
16000 0.33965087
17000 0.33955482
18000 0.3394681
19000 0.33938888
20000 0.33931625
21000 0.33924964
22000 0.3391887
23000 0.33913317
24000 0.33908325
25000 0.33903745
26000 0.3389955
27000 0.33895692
28000 0.33892208
29000 0.33889022
30000 0.33886078
accuracy: 86.68


In [8]:
#kobe_dataset
import pandas as pd
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

x_data = pd.read_csv('kobe_minidata.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x_data = x_data.values
y_data = pd.read_csv('kobe_minidata.csv',usecols=['action_type'])
y_data = y_data.values
#print(x_data)
#print(y_data)

x_test = x_data[0:100:10,:]
y_test = y_data[0:100:10,:]
#print(y_test)

model = DecisionTreeClassifier()
model.fit(x_data,y_data)
print(model)

expected = y_test
predicted = model.predict(x_test)

print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         2
          1       1.00      1.00      1.00         2
          2       1.00      1.00      1.00         2
          3       1.00      1.00      1.00         1
          4       1.00      1.00      1.00         2
          5       1.00      1.00      1.00         1

avg / total       1.00      1.00      1.00        10

[[2 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 1]]


In [15]:
#kobe_dataset
import pandas as pd
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

x = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x = x.values
y = pd.read_csv('kobe_data.csv',usecols=['action_type'])
y = y.values

#print(x_data)
#print(y_data)
x_data = x[1001:30000,:]
y_data = y[1001:30000,:]
x_test = x[0:1000,:]
y_test = y[0:1000,:]
#print(y_test)

model = DecisionTreeClassifier(criterion='gini',splitter='random',max_features=None)
#criterion='gini'\'entropy',splitter='random'\'best',
model.fit(x_data,y_data)
print(model)

expected = y_test
predicted = model.predict(x_test)

print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='random')
             precision    recall  f1-score   support

          0       0.93      0.93      0.93       714
          1       0.53      0.63      0.57       202
          2       0.18      0.07      0.10        58
          3       0.00      0.00      0.00         8
          4       0.33      0.06      0.10        17
          5       0.00      0.00      0.00         1

avg / total       0.78      0.80      0.79      1000

[[667  41   0   0   0   6]
 [ 53 127  14   6   1   1]
 [  0  52   4   1   1   0]
 [  0   6   2   0   0   0]
 [  0  14   2   0   1   0]
 [  0   1   0   0   0   0]]


In [10]:
#kobe_dataset
import pandas as pd
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier

x = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x = x.values
y = pd.read_csv('kobe_data.csv',usecols=['action_type'])
y = y.values

#print(x_data)
#print(y_data)
x_data = x[1001:30000,:]
y_data = y[1001:30000,:]
x_test = x[0:1000,:]
y_test = y[0:1000,:]
#print(y_test)

model = RandomForestClassifier(max_features=None,n_estimators=100)
model.fit(x_data,y_data)
print(model)

expected = y_test
predicted = model.predict(x_test)

print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

/home/z/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:23: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
             precision    recall  f1-score   support

          0       0.92      1.00      0.96       714
          1       0.63      0.59      0.61       202
          2       0.23      0.10      0.14        58
          3       0.00      0.00      0.00         8
          4       1.00      0.06      0.11        17
          5       0.00      0.00      0.00         1

avg / total       0.81      0.84      0.82      1000

[[711   3   0   0   0   0]
 [ 63 120  14   5   0   0]
 [  0  50   6   2   0   0]
 [  0   5   3   0   0   0]
 [  1  13   2   0   1   0]
 [  0   0   1   0 

/home/z/anaconda3/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [17]:
#kobe_dataset
import pandas as pd
from sklearn import metrics
from sklearn.ensemble import GradientBoostingClassifier

x = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x = x.values
y = pd.read_csv('kobe_data.csv',usecols=['action_type'])
y = y.values

#print(x_data)
#print(y_data)
x_data = x[1001:30000,:]
y_data = y[1001:30000,:]
x_test = x[0:1000,:]
y_test = y[0:1000,:]
#print(y_test)

model = GradientBoostingClassifier(n_estimators=100,learning_rate=0.1)
model.fit(x_data,y_data)
print(model)

expected = y_test
predicted = model.predict(x_test)

print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

/home/z/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)
             precision    recall  f1-score   support

          0       0.92      1.00      0.96       714
          1       0.62      0.68      0.65       202
          2       0.00      0.00      0.00        58
          3       0.00      0.00      0.00         8
          4       0.00      0.00      0.00        17
          5       0.00      0.00      0.00         1

avg / total       0.78      0.85      0.81      1000

[[713   1   0   0   0   0]
 [ 65 137   0   0   0   0]
 [  0  58   0   0   0   0]
 [  0   8   0   0   0

/home/z/anaconda3/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [19]:
#kobe_dataset
import pandas as pd
from sklearn import metrics
from sklearn.ensemble import AdaBoostClassifier

x = pd.read_csv('kobe_data.csv',usecols=['loc_x','loc_y','shot_distance',
'shot_zone_area','playoffs','period','minutes_remaining','seconds_remaining',
'shot_type'])

x = x.values
y = pd.read_csv('kobe_data.csv',usecols=['action_type'])
y = y.values

#print(x_data)
#print(y_data)
x_data = x[1001:30000,:]
y_data = y[1001:30000,:]
x_test = x[0:1000,:]
y_test = y[0:1000,:]
#print(y_test)

model = AdaBoostClassifier(n_estimators=100,learning_rate=0.1)
model.fit(x_data,y_data)
print(model)

expected = y_test
predicted = model.predict(x_test)

print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

/home/z/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.1, n_estimators=100, random_state=None)
             precision    recall  f1-score   support

          0       0.92      0.98      0.95       714
          1       0.59      0.70      0.64       202
          2       0.00      0.00      0.00        58
          3       0.00      0.00      0.00         8
          4       0.00      0.00      0.00        17
          5       0.00      0.00      0.00         1

avg / total       0.78      0.84      0.81      1000

[[699  15   0   0   0   0]
 [ 61 141   0   0   0   0]
 [  0  58   0   0   0   0]
 [  0   8   0   0   0   0]
 [  1  16   0   0   0   0]
 [  0   1   0   0   0   0]]


/home/z/anaconda3/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
